language: php

php:
 - 5.3
 - 5.4

before_install:
 - composer self-update
 - php composer.phar install --dev --no-interaction

before_script:
 - cd tests

script:
 - mkdir -p build/logs
 - phpunit
 
after_script:
  - php vendor/bin/coveralls
